random_responses: list[str] = [
    "Hello, World!",
    "Bonjour, le monde!",
    "Salut!",
    "Comment ça va?",
    "Bienvenue!",
    "Ça fait longtemps!",
    "Quoi de neuf?",
    "Bonne journée!",
    "Enchanté!",
    "À bientôt!",
    "Merci!",
    "De rien!",
    "Excusez-moi!",
    "Pas de problème!",
    "Je suis désolé!",
    "Félicitations!",
    "Bonne chance!",
    "Amusez-vous bien!",
    "Prenez soin de vous!",
    "À plus tard!",
    "Bonne nuit!",
    "Bon appétit!",
    "Joyeux anniversaire!",
    "Bon voyage!",
    "Bon retour!",
    "Bon courage!",
    "Bon travail!",
    "Bon week-end!",
    "Bonnes vacances!",
    "Bonnes fêtes!",
    "Bonne année!",
    "Joyeux Noël!",
    "Bonne fête!",
    "Félicitations pour votre réussite!",
    "Je vous souhaite tout le meilleur!",
    "Je suis là pour vous aider!",
    "N'hésitez pas à demander!",
    "Je suis à votre service!",
    "Je suis ravi de vous rencontrer!",
    "C'est un plaisir de vous voir!",
    "Je suis heureux de vous aider!",
    "Je suis là pour vous!",
    "Je suis à votre disposition!",
    "Je suis à votre écoute!",
    "Je suis là pour vous soutenir!",
    "Je suis là pour vous accompagner!",
    "Je suis là pour vous guider!",
    "Je suis là pour vous conseiller!",
    "Je suis là pour vous assister!",
    "Je suis là pour vous servir!",
    "Je suis là pour vous répondre!",
    "Je suis là pour vous informer!",
    "Je suis là pour vous expliquer!",
    "Je suis là pour vous éclairer!",
    "Je suis là pour vous rassurer!",
    "Je suis là pour vous encourager!",
    "Je suis là pour vous motiver!",
    "Je suis là pour vous inspirer!",
    "Je suis là pour vous soutenir moralement!",
    "Je suis là pour vous apporter mon aide!",
    "Je suis là pour vous apporter mon soutien!",
    "Je suis là pour vous apporter mon assistance!",
    "Je suis là pour vous apporter mon expertise!",
    "Je suis là pour vous apporter mon expérience!",
    "Je suis là pour vous apporter mon savoir-faire!",
    "Je suis là pour vous apporter mon savoir!",
    "Je suis là pour vous apporter mes connaissances!",
    "Je suis là pour vous apporter mes compétences!",
    "Je suis là pour vous apporter mes conseils!",
    "Je suis là pour vous apporter mes recommandations!",
    "Je suis là pour vous apporter mes suggestions!",
    "Je suis là pour vous apporter mes idées!",
    "Je suis là pour vous apporter mes solutions!",
    "Je suis là pour vous apporter mes réponses!",
    "Je suis là pour vous apporter mes explications!",
    "Je suis là pour vous apporter mes éclaircissements!",
    "Je suis là pour vous apporter mes précisions!",
    "Je suis là pour vous apporter mes informations!",
    "Je suis là pour vous apporter mes connaissances!",
    "Je suis là pour vous apporter mes compétences!",
    "Je suis là pour vous apporter mes conseils!",
    "Je suis là pour vous apporter mes recommandations!",
    "Je suis là pour vous apporter mes suggestions!",
    "Je suis là pour vous apporter mes idées!",
    "Je suis là pour vous apporter mes solutions!",
    "Je suis là pour vous apporter mes réponses!",
    "Je suis là pour vous apporter mes explications!",
    "Je suis là pour vous apporter mes éclaircissements!",
    "Je suis là pour vous apporter mes précisions!",
    "Je suis là pour vous apporter mes informations!",
    "Je suis là pour vous apporter mes connaissances!",
    "Je suis là pour vous apporter mes compétences!",
    "Je suis là pour vous apporter mes conseils!",
    "Je suis là pour vous apporter mes recommandations!",
    "Je suis là pour vous apporter mes suggestions!",
    "Je suis là pour vous apporter mes idées!",
    "Je suis là pour vous apporter mes solutions!",
    "Je suis là pour vous apporter mes réponses!",
    "Je suis là pour vous apporter mes explications!",
    "Je suis là pour vous apporter mes éclaircissements!",
    "Je suis là pour vous apporter mes précisions!",
    "Je suis là pour vous apporter mes informations!",
]