"""make conversation name non-unique

Revision ID: 877cebb3e5ff
Revises: 14f9c0fbb4ba
Create Date: 2025-02-23 02:09:49.686762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877cebb3e5ff'
down_revision = '14f9c0fbb4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_name')
        batch_op.create_index(batch_op.f('ix_conversations_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_name'))
        batch_op.create_index('ix_conversations_name', ['name'], unique=1)

    # ### end Alembic commands ###
