"""Rename password column to password_hash

Revision ID: b326e708b4c6
Revises: 127720933804
Create Date: 2025-02-21 22:13:11.653329

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b326e708b4c6"
down_revision = "127720933804"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password", new_column_name="password_hash")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password_hash", new_column_name="password")
    # ### end Alembic commands ###
